server:
  port: 9090

spring:
  datasource: # 数据源配置
    name: test
    url: jdbc:mysql://47.101.213.172:3306/mychat?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true  #jdbc:mysql://14.66.87.165:3307/soa_kss
    username: root
    password: 123456 #dddd
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: #redis配置
    database: 0 # Redis数据库索引（默认为0）
    host: localhost  # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 300 # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.onenight.entity  # 注意：对应实体类的路径
