package com.example.onenight.mapper;

import com.example.onenight.entity.ChatMessage;

public interface ChatMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int insert(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int insertSelective(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    ChatMessage selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChatMessage record);
}