package com.example.onenight.mapper;

import com.example.onenight.entity.FriendApply;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface FriendApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer friendapplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int insert(FriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int insertSelective(FriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    FriendApply selectByPrimaryKey(Integer friendapplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendApply record);


    /**
     * @Annotate:通过申请人id和申请对象id查询申请信息状态为在申请的数据数量。
     * @author ztx
     * @date 2020/6/16
     */
    int selectCountByUserId(@Param("userId")int userId,@Param("friendId")int friendId);
}