package com.example.onenight.mapper;

import com.example.onenight.entity.FriendShip;

public interface FriendShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer friendshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbggenerated
     */
    int insert(FriendShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbggenerated
     */
    int insertSelective(FriendShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbggenerated
     */
    FriendShip selectByPrimaryKey(Integer friendshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendShip record);
}