package com.example.onenight.mapper;

import com.example.onenight.entity.FriendApply;

public interface FriendApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer friendapplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int insert(FriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int insertSelective(FriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    FriendApply selectByPrimaryKey(Integer friendapplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendApply record);
}