package com.example.onenight.entity;

import java.util.Date;

public class ChatMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.message_id
     *
     * @mbggenerated
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.send_userid
     *
     * @mbggenerated
     */
    private Integer sendUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.receive_userid
     *
     * @mbggenerated
     */
    private Integer receiveUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.message_val
     *
     * @mbggenerated
     */
    private String messageVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.send_time
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.message_id
     *
     * @return the value of chatmessage.message_id
     *
     * @mbggenerated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.message_id
     *
     * @param messageId the value for chatmessage.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.send_userid
     *
     * @return the value of chatmessage.send_userid
     *
     * @mbggenerated
     */
    public Integer getSendUserid() {
        return sendUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.send_userid
     *
     * @param sendUserid the value for chatmessage.send_userid
     *
     * @mbggenerated
     */
    public void setSendUserid(Integer sendUserid) {
        this.sendUserid = sendUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.receive_userid
     *
     * @return the value of chatmessage.receive_userid
     *
     * @mbggenerated
     */
    public Integer getReceiveUserid() {
        return receiveUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.receive_userid
     *
     * @param receiveUserid the value for chatmessage.receive_userid
     *
     * @mbggenerated
     */
    public void setReceiveUserid(Integer receiveUserid) {
        this.receiveUserid = receiveUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.message_val
     *
     * @return the value of chatmessage.message_val
     *
     * @mbggenerated
     */
    public String getMessageVal() {
        return messageVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.message_val
     *
     * @param messageVal the value for chatmessage.message_val
     *
     * @mbggenerated
     */
    public void setMessageVal(String messageVal) {
        this.messageVal = messageVal == null ? null : messageVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.send_time
     *
     * @return the value of chatmessage.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.send_time
     *
     * @param sendTime the value for chatmessage.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
}