package com.example.onenight.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_power
     *
     * @mbggenerated
     */
    private String userPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_credit
     *
     * @mbggenerated
     */
    private Integer userCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_balance
     *
     * @mbggenerated
     */
    private String userBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_account
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_power
     *
     * @return the value of users.user_power
     *
     * @mbggenerated
     */
    public String getUserPower() {
        return userPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_power
     *
     * @param userPower the value for users.user_power
     *
     * @mbggenerated
     */
    public void setUserPower(String userPower) {
        this.userPower = userPower == null ? null : userPower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_credit
     *
     * @return the value of users.user_credit
     *
     * @mbggenerated
     */
    public Integer getUserCredit() {
        return userCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_credit
     *
     * @param userCredit the value for users.user_credit
     *
     * @mbggenerated
     */
    public void setUserCredit(Integer userCredit) {
        this.userCredit = userCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_balance
     *
     * @return the value of users.user_balance
     *
     * @mbggenerated
     */
    public String getUserBalance() {
        return userBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_balance
     *
     * @param userBalance the value for users.user_balance
     *
     * @mbggenerated
     */
    public void setUserBalance(String userBalance) {
        this.userBalance = userBalance == null ? null : userBalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_account
     *
     * @return the value of users.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_account
     *
     * @param userAccount the value for users.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }


    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", userPower='" + userPower + '\'' +
                ", userCredit=" + userCredit +
                ", userBalance='" + userBalance + '\'' +
                ", userAccount='" + userAccount + '\'' +
                '}';
    }
}